# Generated by Django 3.2.7 on 2021-12-07 16:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('insta', '0005_auto_20211207_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='liked',
            field=models.ManyToManyField(blank=True, default=None, related_name='liked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='like',
            name='val',
            field=models.CharField(choices=[('like', 'like'), ('unlike', 'unlike')], default='like', max_length=50),
        ),
    ]
